import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import ArticleHeader from '../ArticleHeader'

export default function Home() { return (
  <div className={styles.container}>

    <Head>
      <title>Compendium</title>
      <meta name="description" content="Compendium" />
      <link rel="icon" href="../public/hnee-green.png" />
    </Head>

    <main className={styles.mainArticle}>
      <ArticleHeader/>
      <div className={styles.articleContainer}>
        <h1 className={styles.articleTitle}>Seeking a safe and just space for water use in Germany -
how can Germany's national water strategy drive necessary changes?</h1>
        <p id={styles.articleDate}>Updated at 31.08.2022</p>
        <p id={styles.author}>By Linda Schwarz</p>
        <div className={styles.divider}/>

        <div className={styles.articleImageContainer} id={styles.doughnutImage}>
          <img src="/personal-d/GCM personal donuts neu-12 Linda.png" alt="doughnut" height="auto" className={styles.personalDoughnut}/>
          <span>Doughnut showing dimesions affected by this subject</span>
        </div>
        <h2>I. Introduction</h2>
        <p>In the past decades, Central Europe was frequently affected by summer heat and drought periods, which led to low water levels, dried-out soils, and falling groundwater levels also in Germany (UBA, 2021). According to the IPCC's latest climate impact report, extreme weather events such as droughts and heavy precipitation will occur more frequently and also for longer periods than in the past in many regions of Europe and Germany in the future. Furthermore, urbanisation, globalisation, industrial and agricultural practices, demographic changes and biodiversity loss are pressuring ecosystems and have a major impact on water supply and demand (Gerten, 2018). </p>
        <p>In Germany, not only have these global change trends shown that current water use is not secure in the future, but also have current distribution conflicts over water (e.g. over the construction and operation of the Tesla Gigafactory in Brandenburg) and also other social conflicts over the responsibility of poor water quality caused by industry (e.g. through iron clogging of water bodies after brown coal mining) shown that we need to change the way we use and manage water resources and its ecosystems. Speaking in the terminology of the Donut Economy, namely the planetary boundaries of the ecological ceiling and the basic human needs of the social foundation, water use in Germany is neither safe nor just. </p>

        <div className={styles.articleImageContainer}>
          <img src="/linda/1.png" alt="doughnut" height="auto" />
          <span>Fig.1. The components of the development of the National Water Strategy (Own Creation)</span>
        </div>

        <p>German policymakers are trying to meet these challenges by drawing up a national water strategy. A first draft was presented in the summer of 2021, shortly before the elections to the new German parliament. The draft had been preceded by a two-year dialog process with more than 200 stakeholders, as can be seen in Figure 1. Since the new government took office, this strategy has now been supplemented and is expected to be approved by the federal cabinet by the end of the year. In its very own “vision for 2050”, the Federal Ministry for the Environment (BMU) declares: “The protection of natural water resources and the sustainable use of water in times of global transformation are implemented in all areas of life and the economy in Germany for the benefit of people and the environment.” (BMU, 2021, pg. 14)</p>
        <p>To what extent this vision comes close to safe and just water use in the future will be discussed in the following. The National Water Strategy not only includes visions for the future but also sets - according to key strategic issues - goals for action and measures. Since many areas of responsibility for public water supply are in municipal hands, the federal government's sphere of influence alone is limited. Therefore, the strategy aims to address and involve all relevant actors at the federal, state, and local levels. All together has to be seen in a global and European context as the strategy will complement the implementation of various other regulatory or political frameworks, e.g. the Sustainable Development Goals or the European Water Framework Directive. </p>
        <p>Then, the strategy could trigger the following processes, among others:</p>
        <ul className={styles.numberedList}>
          <li>Form a framework for further plans and coordinate action on the topic of water for decision makers and practitioners </li>
          <li>Initiate public debate and a democratic process that can trigger legislation about the goals of the strategy</li>
          <li>Lay the foundation for an overall societal transformation by placing all cross-cutting issues and conflicting goals related to water-use side by side</li>
        </ul>
        <p>The following paper therefore wants to discuss the socio-ecological transformation potential which underlies this strategy to reach a safe and just space for water use in Germany. According to Raworth, that is the space between a social foundation that protects against critical human deprivations and an ecological ceiling that avoids critical natural thresholds. Within this space, both human well-being and the well-being of the planet are ensured - taking into account their interdependence (Raworth, 2012). </p>

        <h2>II. How the National Water Strategy can drive necessary change processes toward just water use contributing to a social foundation </h2>
        <p>Undoubtedly, at its core, the strategy aims to enable a secure and equitable supply of water and all ecosystem services provided by water-related ecosystems in the future. However, the goals and means go well beyond water supply alone, recognizing the multiple dependencies that people have on "water for their food and daily hygiene, ... as a source of energy and means of transport, for industry and agriculture" (BMU, 2021, p. 7). Therefore, integrated management and governance are considered across sectors and scales by taking into account these interdependencies - also referred to as the water-energy-food nexus (FAO, 2014). The central human needs, which are also reflected in this nexus and as addressed by the Social Foundation in the Donut Economy model, are thus also captured by the strategy in numerous areas, as Table 1 summarizes key points: </p>
        <p>In addition to the provision of water through further development of water infrastructure, including the planning of long-distance pipelines (No. 2) or the improvement of forecasting in water balance analysis (No. 5), the strategy also aims to minimize health risks for people by avoiding pollutants in water bodies (No. 4) and considers the coastal region and other ecosystems as a source of food through fisheries (Nr. 6; Nr. 8). </p>
        <p>In addition, some other goals and principles of the strategy contribute to the need for peace and justice. For example, the strategy wants to make those who are responsible for environmental pollution more accountable according to the polluter pays principle (and no longer apply the community pays principle), which could lead to a fairer distribution of damages in a society (basic principles; No. 4). Furthermore, in the future, it should be regulated who is prioritized in the case of water scarcity in the supply and thus aims to prevent distribution conflicts that could endanger (social) peace. </p>
        <div className={styles.articleImageContainer}>
          <img src="/linda/2.png" alt="doughnut" height="auto" />
          <span>Table 1. Components of the social foundation and corresponding selected strategic issues and measures of the National Water Strategy (Own Creation)</span>
        </div>
        <p>For the development of the entire strategy, BMU and UBA conducted the "National Water Dialogue" from 2018 to 2020. Within this framework, discussions were first held with experts, then opinions and perspectives of interested citizens were recorded, and after this, virtual workshops on selected topics of water management were organized, where randomly drawn citizens could express their views at four different locations in Germany. The results of these workshops and an additional youth workshop, together with an online dialogue, most recently formed the basis for a "Citizens' Council" - thus giving a political voice on the topic of water management to the citizen. As seen, through its visions and action points, the strategy addresses multiple human needs and can consequently contribute to shaping water use within the social foundation. </p>

        <h2>How the National Water Strategy seeks to return water use to safe planetary boundaries</h2>
        <p>Almost all planetary boundaries are affected or addressed by the strategy, as Figure 2 shows. This is due to the central role of water in the functioning of the Earth system and human society: Water maintains the integrity of the global biosphere, regulates climate, and mediates carbon and nutrient cycling. At the same time, changes in the water cycle can be felt throughout the Earth system, disrupting processes that interact at numerous levels (Gerten, 2018). In the following, it is briefly described how each limit can be met, and highlights some approaches the National Water Strategy is taking to get back within these safe limits.</p>
        <div className={styles.articleImageContainer}>
          <img src="/linda/3.png" alt="doughnut" height="auto" />
          <span>Fig.2. The 10 strategic goals of the German national water strategy and their addressed planetary boundaries (Own Creation)</span>
        </div>

        <h3>a) Climate Change and Ocean Acidification</h3>
        <p>To return to a safe zone for climate change, we must reduce our carbon dioxide emissions to net zero. Where avoiding emissions is impossible, we must remove them from the atmosphere (negative emissions). The Water Strategy addresses this in several ways, but in particular by linking water, energy and substance cycles (strategic issue Nr. 3). GHG-emissions of the water-infrastructure should be minimised e.g. due to increased water reuse and the transformation toward fossil fuel-free energy production from e.g. wastewater.</p>
        <p>Ocean acidification means that oceans are becoming more and more acidic by decreasing their pH. Since the cause for this is the increase of carbon dioxide in the atmosphere, which dissolves in the water of the oceans, there is various points of focus within the strategy (see above) that primarily address the reduction of CO2 and therefore indirectly address ocean acidification (Helmholtz Klima, 2022b). </p>

        <h3>b) Chemical Pollution</h3>
        <p>To bring the level of extraneous substances back to the safe side of the planetary boundary, their release into the environment must be drastically reduced. This can be achieved e.g. by reducing the amount of waste, safely expanding the circular economy and (gradually) avoiding problematic substances (Helmholtz Klima, 2022b).
The strategy addresses this issue in detail by creating a separate strategic area for mitigating risks caused by substances input (strategic issue Nr.4). Undoubtedly, this is currently quite relevant: Not only do the majority of surface water bodies in Germany anyway still fail to achieve the water quality standards as defined in the EU`s water framework directive, also do more frequent extreme weather hazards or dry periods promote pollution of water bodies, e.g through the dischargement of wastewater into unusual low-flow water bodies. Furthermore it is also to be expected that other pollution will furthermore incline, e.g. due to demographic changes and thus an expected increase of pharmaceuticals use, which traces are discharged into wastewater. All of these substance-related challenges to safe water-use are tackled by already existing extensive national and EU regulations, strategies and action plans, like the European Commission’s zero pollution action plan included in the Green Deal, the Plastics Strategy or the Farm-to-Fork Strategy (National Water Strategy, 2021).</p>
        <p>The National Water Strategy aims to closing any regulatory gaps as well as nourishing a better interaction for implementation of the several regulatory frameworks regarding substances. Another means to be applied here worth mentioning comes from the polluter pays principle, which is among the precautionary principle one of the “basic principles of the strategy” (National Water Strategy, pg. 13). For the prevention of chemical pollution, this would mean for example that manufacturers or distributors of an environmentally harmful product or substance should contribute to the prevention and elimination of the substances and the water damage they cause.</p>

        <h3>c) Nitrogen and Phosphorus loading</h3>
        <p>Although nitrogen and phosphorus are essential for all living things, there is an alarming imbalance of these nutrients worldwide that threatens ecosystems, biodiversity, and human health. Because nutrient fluxes are complex, multiple levers must be considered to bring these nutrient fluxes back into balance, and safe planetary limits are far exceeded. </p>
        <p>The National Water Strategy helps to restore the safe limits, firstly by aiming to intensify the protection of marine areas (the North Sea and Baltic Sea) from land-based pollution (strategic point No. 8). For example, it is proposed to set target values for total phosphorus content at the limnic-marine transition zone. The National Water Strategy helps to restore the safe limits, firstly by aiming to intensify the protection of marine areas (the North Sea and Baltic Sea) from land-based pollution (strategic point No. 8). For example, it is proposed to set target values for total phosphorus content at the limnetic/marine transition point, as such a target value for nitrogen has proven to be a good policy tool to reduce substance input. Second, the strategy proposes closing wastewater loops by linking water, energy, and material loops (strategic point #3) as a solution to keep nitrogen and phosphorus in the environment and available for reuse, e.g. in fertilizers.</p>

        <h3>d) Freshwater withdrawals</h3>
        <p>In science, a distinction is made between blue and green water on earth: While "blue water" is the water in rivers, lakes, groundwater, as well as water stored in frozen form, e.g., in glaciers, "green water," on the other hand, is the plant-available freshwater from soil, rain, and evaporation (Gerten, 2018; Helmholtz Climate, 2022a). According to a recent reassessment published this year led by the Stockholm Resilience Center, the planetary boundary for the global water balance was found to already be at risk from significantly lower soil moisture, or "green water” (Stockholm Resilience Center, 2022). Thus, to return this planetary boundary to a safe zone, special attention to water quality as well as quantity in forests, soils, and landscape water balance must be addressed (Helmholtz Climate, 2022a). </p>
        <p>These findings also appear to have been considered in the current revision of the National Water Strategy. In a recent radio feature on the status of the strategy ‘Steter Tropfen, Nationale Wasserstrategie kommt langsam voran’, the State Secretary in the German Federal Ministry for the Environment, Nature Conservation, Nuclear Safety and Consumer Protection, Stefan Tiedow, addressed the particular relevance of the natural water cycle and that there is a much stronger focus than before on restoring healthy soils and their water storage, and retention properties (Huber, 2022b).</p>
        <p>This is a cross-cutting task, which the National Water Strategy also addresses in various forms, but especially through its strategic point Nr. 5, ‘Manage and restore the semi-natural water balance – prevent conflicting objectives’. But even if no planetary boundary for blue water seems to have been crossed (yet), regional water scarcity must of course be considered and thus addressed in the strategy: Water withdrawals, drainage, hydromorphological changes, soil compaction, and large-scale sealing of land affect and impair the natural water balance. </p>
        <p>A pressing issue that is also widely discussed in public is the question of how to manage water distribution in Germany in the event of regional water shortages and dry soils. Since we are already facing regional water scarcity in many regions of Germany, there is a lack of current solutions to this challenge. To address this challenge, the strategy proposes to first develop a national comprehensive database on water supply and consumption that can serve as a basis for guidelines on rules and criteria for water allocation under regional water scarcity and dry soils. Another important key point of the strategy to balance water withdrawals is to consider the water needs of ecosystems in addition to industrial and agricultural needs. </p>

        <h3>e) Biodiversity loss</h3>
        <p>Biodiversity and healthy ecosystems stabilize the entire Earth system. The loss of global diversity has accelerated dramatically so we have already crossed this planetary boundary. To return to a safe zone, a wide range of anthropogenic stressors must be reduced, whether through climate mitigation, pollution reduction, sustainable landscape, or forest use (Helmholtz Klima, 2022X). The intersections between water use and management are numerous: species and ecosystems are dependent on water supply and quality and freshwater ecosystems are remarkably rich, providing habitat for about 10% of all known living species and one-third of vertebrates, despite covering less than 1% of the Earth's surface (WWF, 2020).</p>
        <p>The synergies between the fight against biodiversity loss and a future secure water supply in Germany are also reflected in some parts of the strategy: For example, it formulates the mission to link biodiversity and ecosystem services provided by healthy ecosystems in connection with water use (strategic issue Nr. 5: Manage and restore the semi-natural water balance– prevent conflicting objectives). In its vision, the strategy addresses, for example, the fact that by 2050, high humus content and high biodiversity in the soil will contribute to a high water storage capacity. The strategy also addresses other measures to protect biodiversity, such as the need to reform agricultural and forestry management practices to ensure long-term water use for the conservation of ecosystems and biodiversity, and the major issue of sustainable management of water bodies, which are particularly important as hotspots for biodiversity (strategic issue #7 Further develop sustainable management of water bodies).</p>

        <h3>f) Land conversion</h3>
        <p>All over the world, forests, wetlands, and other vegetation types are being converted to agricultural and other land uses, affecting many material cycles and important ecosystem services. As a result, the biosphere is increasingly stressed and, as already mentioned, the ability of soils to store water decreases dramatically (Helmholtz Klima, 2022). </p>
        <p>To avoid exceeding this planetary boundary even further, land in use should be restored to its natural state whenever possible and only used or converted when there is no alternative (Helmholtz Klima, 2022a).
Land use change and Water also have several interlinkages, that are also addressed by the National Water Strategy, foremost in its ‘strategic issue Nr. 6 Pursue land use in urban and rural areas that is compatible with water and the climate’.
A target vision by 2050 states the aim to avoid the damage of land-use changes through efficient irrigation, complete avoidance of drains from agricultural land, and sustainable, water-smart agriculture and urban development. It also emphasizes the functions of climate-resilient forests for water storage, erosion control, and flood control.</p>
        <p>The proposed measures include for example the development of a ‘National practical handbook for water-optimised land use’, a dialogue project involving practitioners from agriculture, forestry and the water sector to establish common guiding principles for water-smart agriculture or the implementation of a practice-based model for a water-smart city (sponge city). </p>

        <h2>III. Discussion</h2>
        <p>As we have seen in the numerous visions, missions and action points of the strategy aim at transforming water use in Germany systemically and under the aspects of various ecological aspects. If all the goals addressed in the strategy were to be implemented, we would likely come very close to a safe space for water use while obtaining many desirable co-benefits for climate, food security, and biodiversity. </p>
        <p>The first draft of the Strategy 2021 was welcomed by many environmental NGOs and associations active in Germany (BUND, 2021; DUH, 2021; NABU, 2021; WWF, 2021a). Criticisms were largely overlapping, as can be seen in table 2. Accordingly, the environmental associations unanimously wished for an even stronger focus on the natural water storage functions of river floodplains and forests, which are still too much subject to forestry and agricultural uses and are not vehemently enough opposed by the strategy.</p>
        <div className={styles.articleImageContainer}>
          <img src="/linda/4.png" alt="doughnut" height="auto" />
          <span>Table 2. Main points of criticism regarding the national water strategy from selected NGOs</span>
        </div>

        <p>It must be briefly noted here that the current federal government has determined in its coalition agreement to develop an action program for natural climate protection (ANK), that is expected to be presented in September. The BMU has already presented key points, in which special focus is placed on peatlands and floodplains in their potential for climate protection and many water-related ecosystem services (BMU, 2022; Tagesschau, 2022).</p>
        <p>In summary, it can be said that the national water strategy has certainly already initiated important processes of change towards a safe and just space for water use in Germany by involving various stakeholders in its creation and supporting public and scientific debate. As Waddel (2018) describes in his feature on "Four Strategies for Large Systems Change", this collaborative approach with the instrument of multi-stakeholder dialogues can be attributed to the archetype of the lover. This co-creating role has now come to an end with the drafting of the strategy, as has already been criticized by some NGOs as can be seen in table 2. </p>
        <p>Whether it can set all the necessary change processes in motion, and whether it will do so in time, depends not only on its political, legal, and social implementation but also on the numerous other change processes that are necessary for a socio-ecological transformation, be it in the agricultural or the energy sector. </p>

        <h2>References</h2>
        <ol start="1" className={styles.referenceList}>
          <li>Bundesministerium für Umwelt, Naturschutz, nukleare Sicherheit und Verbraucherschutz. (2022, March 29) Aktionsprogramm Natürlicher Klimaschutz, - Eckpunktepapier- , https://www.bmuv.de/fileadmin/Daten_BMU/Download_PDF/Klimaschutz/aktionsprogramm_natuerlicher_klimaschutz_bf.pdf</li>
          <li>Bundesministerium für Umwelt, Naturschutz, nukleare Sicherheit und Verbraucherschutz. (2021, June). National Water Strategy - Draft of the Federal Ministry for the Environment, Nature Conservation and Nuclear Safety. https://www.bmuv.de/fileadmin/Daten_BMU/Download_PDF/Binnengewaesser/langfassung_wasserstrategie_en_bf.pdf</li>
          <li>Bund für Umwelt und Naturschutz Deutschland e. V.. (2022, June 16). Welt-Dürre-Tag: BUND fordert zügige Verabschiedung der Nationalen Wasserstrategie – Nahendes Hitzewochenende Zeichen der Dringlichkeit [Press release]. https://www.bund.net/service/presse/pressemitteilungen/detail/news/welt-duerre-tag-bund-fordert-zuegige-verabschiedung-der-nationalen-wasserstrategie-nahendes-hitzewochenende-zeichen-der-dringlichkeit/</li>
          <li>Deutsche Umwelthilfe. (2021, June 8). Deutsche Umwelthilfe begrüßt Nationale Wasserstrategie, fordert aber mehr Engagement für den Schutz von Flussauen und Kurswechsel in der Agrarpolitik [Press release]. https://www.duh.de/presse/pressemitteilungen/pressemitteilung/deutsche-umwelthilfe-begruesst-nationale-wasserstrategie-fordert-aber-mehr-engagement-fuer-den-schutz/</li>
          <li>Food and Agriculture Organization of the United Nations. (2014). Water-Food-Energy Nexus | Land & Water | FAO. Retrieved August 20, 2022, from https://www.fao.org/land-water/water/watergovernance/waterfoodenergynexus/en/</li>
          <li>Gerten, D. (2019). Wasser (2nd ed.). C.H.Beck.
Helmholtz Klima. (2022a, July 26). Süßwasser als planetare Grenze: Das blaue und das grüne Wasser. Helmholtz-Klima-Initiative. Retrieved August 14, 2022, from https://helmholtz-klima.de/planetare-grenzen-wasser</li>
          <li>Helmholtz Klima. (2022b, August 2). How we observe planetary boundaries. Helmholtz Climate Initiative. Retrieved August 19, 2022, from https://helmholtz-klima.de/en/planetary-boundaries</li>
          <li>Helmholtz Klima. (2022c, August 12). Why chemicals and plastics pose a risk to our future. Helmholtz Climate Initiative. Retrieved August 20, 2022, from https://helmholtz-klima.de/en/planetary-boundaries-novel-entities</li>
          <li>Huber, E. (2022a, July 19). Kommunen und Dürre: Kommt die Wasserstrategie zu spät? tagesschau.de. Retrieved August 15, 2022, from https://www.tagesschau.de/inland/gesellschaft/wasserknappheit-121.html</li>
          <li>Huber, E. (2022b, August 05). Steter Tropfen... Nationale Wasserstrategie kommt langsam voran. [Radio broadcast]. Deutschlandfunk Kultur. https://www.deutschlandfunkkultur.de/steter-tropfen-nationale-wasserstrategie-kommt-langsam-voran-dlf-kultur-cb86859d-100.html</li>
          <li>Naturschutzbund Deutschland e.V. (2021, June 9). NABU zur Nationalen Wasserstrategie: Ambitionierte Strategie, die schnell umgesetzt werden muss [Press release]. https://www.nabu.de/presse/pressemitteilungen/http/index.php?popup=true&show=31872&db=presseservice</li>
          <li>Umweltbundesamt. (2021). Niedrigwasser, Dürre und Grundwasserneubildung, Bestandsaufnahme zur gegenwärtigen Situation in Deutschland, den Klimaprojektionen und den existierenden Maßnahmen und Strategien, Abschlussbericht.
https://www.umweltbundesamt.de/sites/default/files/medien/1410/publikationen/2022-01-17_texte_174-2021_niedrigwasser_duerre_und_grundwasserneubildung.pdf</li>
          <li>Raworth, K. (2012) A Safe and Just Space for Humanity: Can we live within the doughnut?, Oxfam Discussion Papers,  https://www-cdn.oxfam.org/s3fs-public/file_attachments/dp-a-safe-and-just-space-for-humanity-130212-en_5.pdf</li>
          <li>Stockholm Resilience Centre. The nine planetary boundaries. (2016). Stockholm Resilience Centre. Retrieved August 16, 2022, from https://www.stockholmresilience.org/research/researchnews/tippingtowardstheunknown/thenineplanetaryboundaries.4.1fe8f33123572b59ab80007039.html</li>
          <li>Waddel, S. (2018) Feature - Four Strategies for Large Systems Change. Stanford Social Innovation Review. http://humanisticmanagement.international/wp-content/uploads/2018/06/SSIR-FT_SocialTrans-2.pdf</li>
          <li>World Wide Fund for Nature. (2021a, June 8). Macht Wasser zum Querschnittsthema! [Press release]. https://www.wwf.de/2021/juni/macht-wasser-zum-querschnittsthema</li>
          <li>World Wide Fund for Nature. (2021b, November 25). UMK nutzen für den umweltpolitischen Aufbruch [Press release]. https://www.wwf.de/2021/november/umk-nutzen-fuer-den-umweltpolitischen-aufbruch</li>
        </ol>
      </div>
    </main>
  </div>
) }
