import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import ArticleHeader from '../ArticleHeader'

export default function Home() { return (
  <div className={styles.container}>

    <Head>
      <title>Compendium</title>
      <meta name="description" content="Compendium" />
      <link rel="icon" href="../public/hnee-green.png" />
    </Head>

    <main className={styles.mainArticle}>
      <ArticleHeader/>
      <div className={styles.articleContainer}>
        <h1 className={styles.articleTitle}>Challenges of managing forest reserves: case study of Atewa range forest reserve, Ghana</h1>
        <p id={styles.articleDate}>Updated at 29.08.2022</p>
        <p id={styles.author}>By Madeleine Maomou</p>
        <div className={styles.divider}/>

        <div className={styles.articleImageContainer} id={styles.doughnutImage}>
          <img src="/personal-d/GCM personal donuts-26 Madeleine.png" alt="doughnut" height="auto" className={styles.personalDoughnut}/>
          <span>Doughnut showing dimesions affected by this subject</span>
        </div>
        <h2>I. Introduction</h2>
        <p>Forests provide us with shelter, livelihoods, water, food and fuel security. All these goods valuable directly or indirectly involve forests. Some processes are easy to figure out such as fruits, paper and wood obtaining from trees. Others are less obvious, such as by-products that go into many items like medicines, cosmetics and detergents. Looking at it beyond our narrow, human and urban perspective, forests provide habitats to diverse animal species. They are home to over half of the world’s terrestrial biodiversity and they also form the source of livelihood for many different human settlements, including 60 million indigenous people.</p>
        <p>Africa is the second largest continent on earth and has a very diverse ecosystem. About 22% of the African Continent is actually occupied by forests and woodlands, estimated at 650 million hectares of Africa’s land area, according to the Food and Agriculture Organization of the United Nations (the FAO). This also plays a large role on the global scale accounting for about 17% of the total global forest cover. Despite the fact that a very small percentage of the forest is protected, Africa’s Forest area still plays a very important role in the provision of resources from a human standpoint, and it is a reservoir of great biological diversity within its ecological landscapes. </p>
        <p>Deforestation led to an annual loss of 4.4 million hectares of forest in Africa between 2015 and 2020. These extremes of human activities add the increasing degradation of our planetary home. Human activity is putting unprecedented stress on Earth’s life-giving systems. Global average temperature has already risen by 0.8°C, and we are on track for an increase of almost 4°C by 2100, threatening a scale and intensity of floods, droughts, storms and sea-level rise that humanity has never before witnessed (Raworth,2017) The conversion of forest to other land uses affected mostly the eastern and southern areas of the continent, at a deforestation rate of 2.2 million hectares per year. According to Ghanaian official sources, within the last century alone, Ghana’s forest cover was reduced from 8.2 million ha to 1.7 million ha (Glastra,1999). This obviously has a direct impact on the over 2.5 million people who depend on the forest for its services. </p>
        <p>Forest loss is also a direct contributor to the greenhouse effect and results in global warming. During deforestation, a huge number of trees will be lost. Hence, the lower number of trees will absorb less carbon dioxide, due to which the amount of carbon dioxide in the atmosphere will increase. The greenhouse gases such as carbon dioxide gas absorb the sun’s heat rays reflected by the earth. Therefore, it is very important to have a good management of our forest reserve. </p>

        <h2>II. The Atewa range forest reserve</h2>
        <p>A forest reserve refers to a forest that has been accorded a certain level of protection against unauthorized usage by individuals and groups of individuals. Such reserves are usually protected under the laws of the particular country where it is situated. In other words, activities such as hunting and grazing are strictly prohibited except by expressed permission from relevant traditional and government bodies. Within the high forest zone of Ghana, approximately 1.76 million ha of forest, constituting about 21% of the land area, are permanently protected. Unfortunately, most the protected areas have come under severe pressure as institutions tasked to ensure their effective management are poorly resourced and unable to execute their mandate effectively (Jachmann, 2008; Ntiamoa-Baidu, 2008).</p>
        <p>This paper analyzes the challenges of the management in the Atewa Range Forest Reserve, with specific reference to the institutional context, pressures and threats facing the reserves, as well as forest management and livelihood-conflicts. </p>
        <p>The Atewa Range Forest, located in the Eastern Region of Ghana and 90 km north of Ghana’s capital Accra, forms part of the Upper Guinean forests of West Africa. It covers an area of 23 663 ha. It is one of only two reserves with upland evergreen ecosystem forest classification in Ghana. The Atewa Forest Range, consists of a core zone designated as “Atewa Range Forest Reserve” and a surrounding buffer zone delineated at 200 m altitude. The Atewa forest reserve is fringed by over 40 communities.</p>

        <div className={styles.articleImageContainer}>
          <img src="/madeleine/1.png" alt="doughnut" height="auto" />
          <span>Fig.1. Map of the Atewa Range in Eastern Ghana, showing the Forest Reserve’s boundaries in green, and the rivers highlighted in blue. Source: Save Atewa. </span>
        </div>

        <p>The Atewa Forest Reserve is home to the springs of three rivers which makes it the most important water tower in Ghana, providing water for over 5 million Ghanaians on a daily basis. Illegal gold mining activities are already threatening the water supply, as quality monitoring and assessment of major rivers by Ghana’s Water Research Institute confirmed in May 2017. This is highly likely to get worse when bauxite mining starts in the area.</p>
        <p>Many of the plant species occur only in this part of Ghana or in few other localities and some were declared as a specially protected GSBA (Globally Significant Biodiversity Area) following a national botanic survey of forest reserves by Ghana Forestry Dept. in the 1990s.[3] The forest reserve contains many birds that are rare elsewhere in Ghana including Olive Long-tailed Cuckoo, Rufous-sided Broadbill, Least Honeyguide, Spotted Honeyguide, Common Bristlebill and Blue-headed Crested-Flycatcher.[4] In a 2006 expedition to survey the reserve, scientists discovered two rare and possibly endangered species of primate in the reserve: Geoffroy's pied colobus (Colobus vellerosus) and the olive colobus Procolobus verus, as well as 17 rare butterfly species and the critically endangered frog species Conraua derooi. Butterfly species include the Papilio antimachus  which has the widest wingspan in the world and the Mylothris atewa, which may be globally critically endangered.[5]</p>

        <h2>III. Management challenges of Atewa Range Forest Reserve</h2>
        <p>Changes in land cover of protected areas and their buffers have serious implications on the conservation of biodiversity within such biomes because land use has been recognized as one of the major drivers of biodiversity change. The Atewa Range Forest Reserve is one of Ghana's Upper Guinea Forests declared as a Globally Significant Biodiversity Area (GSBA). But the reserve is under threat from several human disturbances which could impact on the land cover of the reserve. </p>
        <p>In recent decades, the Atewa Forest Reserve has been under pressure by a number of threats, such as farm encroachment, which is restricted since a few years now, bushmeat hunting, illegal and unsustainable logging, artisanal gold mining (referred to as ‘galamsey’ in local language), and lastly, bauxite mining and exploration. All of these factors undermine the river’s capacity to absorb and filter rainwater. The last factor listed is increasingly becoming a concern for officials and locals alike, especially given the new MoU with China.</p>
        <p>In The doughnut economy, the concept of social equity and work income are the most important aspects to face in this context of Atewa Range Forest reserves concerning the social foundation aspect. From 2008 to 2016, most of the illegal gold mining took place around the edges of the Atewa Forest Reserve. Many locals upstream did not have much choice other than illegally digging for gold, as claimed by Ntiamoa Eric, an artisanal gold miner speaking to A Rocha Ghana (one of the organizations that published the joint call to their government) “In reality, there are no jobs in this village. Growing cocoa is the only other job we have here. We might look young but we all own small cocoa farms. But cocoa farming is such you need other source of income to support it.” Source: A Rocha Ghana.</p>
        <div className={styles.articleImageContainer}>
          <img src="/personal-d/GCM personal donuts-26 Madeleine.png" alt="doughnut" height="auto" className={styles.personalDoughnut}/>
          <span>Fig.2. The Doughnut of social and planetary boundaries</span>
        </div>

        <h2>IV. Socio-economic aspects</h2>
        <p>Though the Atewa Range Forest Reserve has now been declared as a Globally Significant Biodiversity Area (GSBA), there are still several infractions on the reserve. These include bauxite mining, illegal lumbering, illegal small-scale mining, hunting and farming among others. Even if after several attempts at mining the bauxite exploitation has not been successful. The other human activities are taking place covertly within the reserve and indiscriminately at the fringes, and this may impact on the vegetative cover of the reserve which has far reaching consequences on biodiversity.</p>
        <div className={styles.articleImageContainer}>
          <img src="/madeleine/3.png" alt="doughnut" height="auto" className={styles.personalDoughnut}/>
          <span>Fig.3. An illegal artisanal gold mine on the edges of the Atewa Forest Reserve. Source: A Rocha Ghana. </span>
        </div>
        <p>An anti-galamsey task force deployed by the government under the name “Operation Vanguard” enforces the country’s laws against illegal practice of gold mining. While around 100 illegal miners have been arrested as of August 10, 2017, the anti-illegal mining task force is “facing stiff opposition from illegal miners“. The Ghanaian government is said to spend around fifty million Ghana cedis around 11 million USD, on the anti-galamsey campaign, Ghana Web reported.</p>

        <h2>V. Socio-cultural aspects</h2>
        <p>The reserve has been managed under the protection working circle system of the then Forestry Department, now Forest Service Division ,where an area is managed with the intention of protecting the watershed and no logging is allowed. Atewa was designated as a Special Biological Protection Area in 1994. In 1995 it was reclassified as a Hill Sanctuary under the Forest Protection Strategy proposals. In 1999, Atewa was again redesignated as one of the 30 Globally significant biodiversity Areas (GSBAs). It is also among the 36 important Bird Areas (IBAs) in Ghana as designated by Birdlife International (Ntiamoa-Baidu et al.2001).</p>
        <p>The culture of the forest fringe communities is inextricably linked with the existence of the Atewa reserve. The forest is regarded as the home of the ancestral spirits, who provide protection, success and progress for the AKYEM ABUAKWA people. Some animals are regarded as totems by certain clans. Taboos such as avoidance of farming activities along river banks are all indications of the socio-cultural significance of forest resources. Forest fringe communities also depend on the forest for non-timber forest products, some of which are extracted in large quantities for sale. Several streams and headwaters of major rivers like the Densu, Avenu and Birim serve as important sources of drinking water to a large number of people within and outside the traditional area, including Accra and other urban areas. Many individuals, institutions and communities hold a stake in the continued existence of the reserve. </p>

        <h2>VI. Ecological aspects</h2>
        <p>In the Doughnut economy planetary boundaries, Land conservation, climate change and biodiversity loss are the mean aspect to be considered in the Atewa Range Forest Reserve. Cropping practices which encourage intensive use of the same piece of land over a prolonged period of time have led to leaching and loss of soil fertility in parts of Atewa. In local villages, deep channels have been created by surface water running over ground lacking plant cover. In the Theory of the doughnut economy it is mentioned that Around 40 percent of the world’s agricultural land is now seriously degraded, and by 2025 two out of three people worldwide will live in water-stressed regions (Raworth, 2017.P.3). Within some of the villages, erosion has eaten away the foundation cover of houses, and in some cases washed away whole streets, bridges and other services. Illegal logging has been prevalent in Atewa, especially during the 1990s, leading to further problems with erosion throughout the area. Indeed in 2001, logging escalated so much that the Ghanian army was called to help protect the reserve from loggers (Hawthorne, 2002).</p>
        <p>Unsustainable exploitation of forested area, coupled with the relatively high prevalence of bush fires, has resulted in the depletion of important timber species. The scale of biodiversity loss is severe: species extinction is occurring at least ten times faster than the boundary deems safe. No wonder that, since 1970, the number of mammals, birds, reptiles, amphibians and fish worldwide has fallen by half (Raworth, 2017, p18). Although the global scale of chemical pollution has not yet been quantified, it is of great concern to many scientists.’’ Trees such as mahogany, Odum, Obeche, and Emire, which were abundant before the 1960s are now locally rare. At least 954 ha (4.1%) of Atewa was converted to plantation through the taungya program between 1954 and 1975(Hawthorne2002). Most of these plantations have since been abandoned and remain as severely degraded areas covering most of the slopes of the reserve.  A 2002 bushmeat market survey targeting the major bushmeat markets in both Accra and Kumasi indicated that about 15% of the bushmeat found in these markets comes from the Atewa  forest(Conservation International-Ghana 2001, 2002).</p>
        <p>Most of the species sold are wholly protected in Ghana (i.e., Black-and-white colobus, Spotted palm civet, Giant and Long-tailed pangolins). In addition, the survey revealed that some traditional sacred animals (totems) such as the Crested porcupine (totem of the Ashantis) are being hunted and sold. A number of bushmeat markets are in existence in close proximity to Atewa. The largest roadside bushmeat market in Ghana is at Anyinam, at the fringe of the Atewa, where bushmeat is sold throughout the year. Hunters illegally entering Atewa are known to use automatic rifles, poisonous chemicals, traps and fires. Atewa is dissected by many rivers and their tributaries. However, human activities in the form of farming, deforestation, and to some extent mining, have now polluted and silted up many of these waterways. The effluents of the many small-medium scale oil palm-processing factories in the area are also a major cause of water pollution. In order to secure adequate amounts of water for their operations, many of these factories are located on the banks of streams where water can be more easily obtained. Oily waste matter from the factories is then washed into the streams, especially at Kade, Boadua, Wenkyi and Mepom. Furthermore, the forests that shelter these waterways have been cleared, with many rivers and streams experiencing greater rates of evaporation for longer periods of the year. Hence, they are now increasingly unable to satisfy the water requirements of the communities they are supposed to serve.</p>

        <h2>VII. Actors involved</h2>
        <p>Beyond the Government, there are many other international organizations involved as well in the proper management of this Range Forest Reserve. These managements represent an essential aspect to be considered for many social and ecological reasons. These include:</p>
        <ul className={styles.numberedList}>
          <li>A Ghanaian-government-sponsored Presidential Initiative on tree Plantations project: seeks to rehabilitate degraded forest areas. </li>
          <li>February 2020, a group of international alumnae using companies including BMW Group, Tetra Pak and Schueco International wrote to local community groups around Atewa who are opposed to bauxite mining, expressing their concern about the mining plans and showing their support for calls to save Atewa.</li>
          <li>2012, the three-year Atewa Critical Conservation Action Programme (ACCAP), funded by A.G. Leventis Foundation, was initiated in a bid to lessen these threats. The program carried out significant awareness-raising and advocacy activities which resulted in greater international as well as local visibility of the threats to Atewa. As a result, a conservation strategy that fosters long-term actions for the protection of Atewa Forest and its watershed catchments has been facilitated. Significantly, the work undertaken by A Rocha under ACCAP has leveraged support, participation and funding from other agencies for the conservation of Atewa Forest, in particular in working with IUCN Netherlands in a major Dutch-funded program entitled Living Waters from the Mountain: protecting the Atewa Water Resources. Support from the Dutch Government has enabled A Rocha to run a substantial public campaign for the protection of Atewa, urging the government to set the forest aside from bauxite mining plans and instead make it a National Park (A Rocha Ghana ,2020).</li>
        </ul>

        <h2>Time frame and level of the project</h2>
        <p>Over the last 90 years, the Atewa has been recognized as an important reservoir of biodiversity and has been officially classified in various ways: as a national forest reserve in 1926, a Special Biological Protection Area in 1994, a Hill Sanctuary in 1995 and as one of Ghana’s 30 Globally Significant Biodiversity Areas (GSBAs) in 1999. In 2001, Atewa was listed as an Important Bird Area (IBA) by Birdlife International (Okyeame Ampadu-Agyei, 2001). </p>
        <p>Therefore, the main objective is to achieve a long-term (10-50 years) protection and sustainable management of Atewa forest as a public good for securing livelihoods and water management, mitigating climate change impacts and conserving global biodiversity.</p>
        <p>The level and the lack of participation of local stakeholders in decision making and management of this forest reserve in combination with a lack of direct economic benefits from the reserve are the main divers for local encroachment and illegal activities. On the national level it is a mix of conflicting policies compromising the protection of Atewa forest, weak policy implementation and compliance by various actors and political interests, from local to national level, in quick economic benefits deriving from logging and mining that put Atewa at risk. It is consequently obvious that the project of the management challenges of Atewa range forest is now an international level, where several international organizations are involved in the proper management of this forest and the livelihood of it surrounding communities.</p>

        <h2>Applicable in other level</h2>
        <p>Forests provide an array of benefits to human societies above and beyond their pivotal roles as habitat and environmental regulators in natural ecosystems. it is obviously important that this approach could effectively be applied in many other forests reserve, for example, on the forest of Congo Basin in central Africa which covers more than 180 million hectares, the second largest tropical rainforest block after the Amazon rainforest. More than 65 million people are directly dependent on that forest for livelihood. In addition, the Congo Basin Forest is the habitat of more than 400 mammal species, more than 1,000 bird species and 20,000plant species. Many plant and animal species are endemic to the Congo basin. </p>
        <p>Therefore, considering the amount of biodiversity in these forests, it is very important to apply as an approach Community forests to drive improvement of livelihoods and wellbeing in forest communities, as well as biodiversity protection and reduced deforestation in target areas in DRC, providing a scalable model for nationwide implementation.</p>

        <h2>Personal impression</h2>
        <p>Despite the high level of protection given to national parks and other protected areas, many are not functioning well as originally envisioned owing to ecological pressures such as fires, floods, climate regimes, and expansion of human activities on lands surrounding protected areas. Therefore, there can still be an option to provide income, for example: </p>
        <p>Ecotourism is likely the best option for bringing income to the region, particularly to Kibi, by transforming the Atewa forest into a world-class ecotourism center, which will focus on the rare and beautiful species identified during the RAP survey and other studies.</p>
        <p>Research station to facilitate research of Atewa and surroundings by Ghanaian and international scientists, promoting collaborations and training biology and natural resource management students:</p>
        <ul className={styles.numberedList}>
          <li>Sustainable employment opportunities for local community members as builders, managers, for maintenance and housekeeping, tour guides, researchers, and research assistants.</li>
          <li>Other potential alternative-income industries</li>
          <li>Butterfly farming - sale of living butterfly pupae to the global market</li>
          <li>Beekeeping - producing honey for local consumption and for sale</li>
          <li>Farming of native ornamental fishes for the aquarium trade</li>
          <li>Producing products for the tourist trade such as baskets, Kente cloth weavings, or wood carvings</li>
          <li>Alternatives to bushmeat hunting, such as raising other types of animals for meat</li>
        </ul>

        <h2>Conclusion</h2>
        <p>This study has presented the proposition needed of Atewa, an important forest reserve in the East of Ghana, due to the current pace of degradation by illegal logging which constitutes the highest scoring pressure and highest threat to conservation, followed by agricultural encroachment and adjacent land-use. The economic income from mining must be balanced with environmental and social concerns, hence the need for the country to pursue initiatives and investments that secure the ecological integrity of the forests. Current estimates suggest that human population density is, or will become, a serious issue for some of the world’s most biodiverse areas, including the remaining tropical lowland forests. Mining activities by unlicensed individuals and groups are increasing and causing serious problems for communities. Major pollution occurs downstream from water bodies along whose banks mining takes place, as a result of improper mining practices. The most affected is the Birim River which suffers from pervasive sediment loading. It is important to protect our forest against all forms of environmental threats in the sake of our own well-being.</p>
        <p>Forest conservation in Ghana has played a significant role in protecting the remaining forests, especially in the high forest zone. Local livelihood issues and national economic aspirations coupled with weak institutions have, however, posed major challenges to the effective conservation of the reserves. Greater involvement of local people and support to the private sector that provides increased livelihood opportunities for the poor, especially those living close to forest reserves, would help reduce forest exploitation.</p>
        <p>Finally, traditional authorities, namely village elders and chiefs, should be empowered to prosecute offenders when caught. Chiefs known to be in the habit of condoning illegal activities should face severe sanctions. Atewa should be a National Park to provide present and future natural resources to generations.</p>

        <h2>References</h2>
        <ol start="1" className={styles.referenceList}>
          <li>Akadimagazine,	 (2020). Reasons to protect Atewa Forest Reserve akadimagazine.com2020)  available at https://www.akadimagazine.com/post/reasons-to-protect-atewa-forest-reserve.(accessed 20 July 2022)</li>
          <li>Domfeh, K. A (2013).  Mineral resource exploitation in Atewa Forest Reserve challenged modernghana.com available at https://www.modernghana.com/news/454806/mineral-resource-exploitation-in-atewa-forest-reserve-challe.html (accessed 15 July 2022).</li>
          <li>Faria, J. (2022). deforestation rate in Africa by region statistic. available at https://www.statista.com/statistics/1286878/deforestation-rate-in-africa-by-region/ (accessed 20 July 2022).</li>
          <li>"Forest Resources." Environmental Science: In Context. Retrieved August 02, 2022 from Encyclopedia.com: https://www.encyclopedia.com/environment/energy-government-and-defense-magazines/forest-resources.</li>
          <li>Kusimi, J. M. (2015). Characterizing land disturbance in Atewa Range Forest Reserve and Buffer Zone - ScienceDirect available at   https://www.sciencedirect.com/science/article/abs/pii/S0264837715002550 (accessed 15 July 2022).</li>
          <li>Ntim, A. (2021). An important forest reserve in Ghana -The Atewa Range My Ghana Daily available at https://myghanadaily.com/an-important-forest-reserve-in-ghana-the-atewa-range/ (accessed 20 July 2022)</li>
          <li>Raworth, K. (2017). Seven ways to think like a 21st century economics. Chelsea Green publishing.</li>
          <li>Rocha Ghana (2020). Protecting atewa forest. A Racha Ghana available athttps://ghana.arocha.org/projects/protecting-atewa-forest/</li>
          <li>Sekoni, R. (2019). Africa's forests thinkafrica.net  available at   https://thinkafrica.net/africas-forests/ (accessed 18 July 2022).</li>
          <li>Sebastian, P. (April 2022). Bauxite mining at Atewa Forest Reserve, Ghana: a political ecology of a conservation-exploitation conflict researchgate.net available at https://www.researchgate.net/publication/344614135_Bauxite_mining_at_Atewa_Forest_Reserve_Ghana_a_political_ecology_of_a_conservation-exploitation_conflict (accessed 16 July 2022).</li>
          <li>Triebert, C. (2017). Ghana's Atewa Forest: Monitoring Mining Which May Threaten Water Sources bellingcat available at https://www.bellingcat.com/news/africa/2017/08/14/mining-in-the-atewa-forest/(Accessed 20 Juin 2022).</li>
          <li>USAID.gov. (2020).  Forests for the future available at https://www.usaid.gov/democratic-republic-congo/fact-sheets/forests-future. (Accessed 15 July 2022).</li>
        </ol>
      </div>
    </main>
  </div>
) }
