import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import ArticleHeader from '../ArticleHeader'

export default function Home() { return (
  <div className={styles.container}>

    <Head>
      <title>Compendium</title>
      <meta name="description" content="Compendium" />
      <link rel="icon" href="../public/hnee-green.png" />
    </Head>

    <main className={styles.mainArticle}>
      <ArticleHeader/>
      <div className={styles.articleContainer}>
        <h1 className={styles.articleTitle}>The German Renewable Energy Sources Act (EEG)</h1>
        <h1 className={styles.articleSubTitle}>A Success Story for Accelerating the Energy Transition?</h1>
        <p id={styles.articleDate}>Updated at 04.09.2022</p>
        <p id={styles.author}>By Simon Schreck</p>
        <div className={styles.divider}/>

        <div className={styles.articleImageContainer} id={styles.doughnutImage}>
          <img src="/personal-d/GCM personal donuts neu-22 Simon.png" alt="doughnut" height="auto" className={styles.personalDoughnut}/>
          <span>Doughnut showing dimesions affected by this subject</span>
        </div>
        <h2>I. Introduction</h2>
        <p>In international contexts Germany is often termed as a role model for the energy transition, i.e. for the transformation to a renewable and emission free energy system. (Römermann & Kemfert, 2020; Diermann, 2020) Looking at the evolution of renewable energy sources in Germany and compared to other countries (see Figure 1) this statement definitely holds true. Starting from the year 2000 the share of renewables in Germanys electricity mix increased from a mere 5% in 2000 to around 40% in 2020. (UBA, 2022c) This evolution is exceptional among other industrialized as well as developing countries (compare Figure 1). While it was behind most other countries in terms of share of renewables in 2000, Germany is among the leaders in this figure today.</p>
        <p>The onset of the rise in renewable energy in the year 2000 by now surprise falls together with the adoption of the German Renewable Energy Sources Act. This compendium contribution shall explain the mechanisms that lay behind this act and how they drove and still drive the energy transition in Germany. It shall also critically reflect on its success and impact in Germany and internationally.</p>
        <p></p>

        <div className={styles.articleImageContainer}>
          <img id={styles.narrowImage} src="/simon/4.png" alt="doughnut" height="auto" />
          <span>Fig.1. (a) Share of renewable electricity production in different countries and in Europe from 1985 until today. (b) Renewable energy generation for different sources in Germany from 1985 until today. Own creation with data taken from (Ritchie, 2020).</span>
        </div>

        <h2>II. The German Renewable Energy Sources Act (EEG)</h2>
        <p>The German Renewable Energy Sources Act (abbreviated with ‘EEG’ in the following from its German name Erneuerbare-Energien-Gesetz) is the central tool of Germanys transition to a carbon free energy system. The EEG came into place in the year 2000 as the successor to the 1991 Electricity Feed Act (Stromeinspeisungsgesetz). (EEG 2021, 2021; Bundesanzeiger, 1990) Before 1991 the German energy system was exclusively based on large centralized power plants running predominantly on coal, gas and nuclear power. The Electricity Feed Act for the first time set out rules for electricity supply companies and obliged them to feed into their grids and pay for electrical energy from renewable sources of (small) third-party suppliers. ‘The goal of the EEG [was] to speed up the market launch of technologies for [renewable] electricity production’. (Gröschel & Geheeb, 2007) More specifically and according to § 1, sentence 1, the purpose of the EEG is,</p>

        <ul start="1" className={styles.numberedList}>
          <li>to enable sustainable development of the energy supply, in particular in the interest of climate and environmental protection.</li>
          <li>to reduce the economic costs of energy supply, also by including long-term external effects</li>
          <li>to conserve fossil energy resources and</li>
          <li>to promote further development of technologies for generation of electricity from renewable energy sources.’ (EEG 2021, 2021)</li>
        </ul>

        <p>To achieve these goals, the EEG had three central pillars. The first was a fixed guaranteed feed-in tariff for electricity from renewable sources in combination with a prioritization of renewable electricity over electricity from conventional sources like nuclear power, coal, and gas in the dispatching schemes of electricity supply companies. The fixed feed-in tariff was set higher than the average market price for electricity and guaranteed for 20 years. This means that owners of renewable energy sources could be sure that they can feed-in and sell their electricity to an above market price. Hence, the EEG created strong incentives and securities to invest in renewable energy power plants. The financing of the above-market feed-in tariff was realized by the so-called EEG surcharge (EEG Umlage), which was applied to the electricity price for all end consumers irrespective of the source of electricity. The EEG surcharge was adjusted each year based on the actual difference between the fixed feed-in tariffs and the electricity market prices. Though, over the course of several EEG revisions (see below), the feed-in tariff scheme was mostly exchanged for an auction scheme to enhance competition and ensure lowest possible prices for renewables on the market, the overall concept of an above market price for renewable energy source owners stayed the same.</p>
        <p>The second pillar of the EEG was a reduction of the fixed feed-in tariffs over time (first year by year, later month by month), called degression. This means that even though the tariff for a given renewable power plant was guaranteed for 20 years, a renewable power plant connected to the network in e.g. the year 2005 would get a higher feed-in tariff than a power plant connected one year later. This was for one to account for the generally falling prices of renewable energy sources and for the other to incentivizes technological innovation that reduces production costs.</p>
        <p>The third pillar was a set of technology-specific deployment corridors that defied the share each technology should take in the overall national electricity mix up to the year 2050. The lower and upper targets in these corridors were raised over the course of the last 20 years constantly. The latest version of the EEG states in § 4 that in 2030, 71 GW of onshore wind energy, 100 GW of photovoltaics and 8.4 GW of biomass plants are to be installed. This means that 65 percent of gross electricity consumption is to come from renewable energy in 2030. Before 2050, all electricity generated or consumed in Germany is to be generated in a greenhouse gas-neutral manner. (EEG 2021, 2021; UBA, 2021)</p>

        <h2>III. The EEG and Donut Economy</h2>
        <p>To be very clear: The EEG is not based on the theory of donut economy. By contrast, it is based on a (somewhat regulated) market economy and makes use of mechanisms of a more or less free market such as competition and profit maximization. However, the EEG can still be analyzed within the donut economy theory and does, at least in parts, contribute to elements of the theory.</p>
        <p>The EEG, seen as a project, is a long-term project of remodeling Germanys energy landscape. The deployment corridors for the different renewable energy technologies set targets up to the year 2050. The degression of feed-in tariffs and the flexible EEG surcharge were supposed to guarantee a cost effective and efficient support scheme for renewable technologies over a long period of several decades. One key to the long-term success of the EEG is its high flexibility and many revisions and extensions that have been implemented over its lifetime. Since 2000 a total of seven major revisions of the EEG were published including a special revision just for the photovoltaics sector in 2012. In addition, a special act dealing with offshore wind energy followed out of these revisions in 2017. (BMWK, 2022d) Over the course of these revisions the support mechanisms were continuously adjusted to account for increasing technology development and market penetration and with this keep up pressure on the manufacturers of the corresponding technologies to continuously reduce the generation costs for electricity from renewable energies. In the mid to long term the aim is that electricity from renewable energies becomes competitive and traded directly without having to rely on guaranteed feed-in tariffs. (BMWK, 2022e)</p>
        <p>Though the legislation of the EEG is national wide, its practical implementation happens on a very local and regional level. The EEG provides support for a variety of actors that want to invest in renewable energies ranging from single-family home owners putting a few solar panels onto their rooftop up to large national and international corporations investing in multi-million euro solar and wind park projects. However, also for these large-scale projects the actors involved in its implementation are local communes and citizens as owners of the respective land, regional distribution network owners responsible for feeding the generated electricity into the national power network and often also local or regional highly specialized planning and construction companies building the actual installations.</p>

        <h2>IV. Contributions to the Donut</h2>
        <p>One of the main aims of the EEG is ‘to enable sustainable development of the energy supply, in particular in the interest of climate and environmental protection.’ (EEG 2021, 2021) This interest of climate and environmental protection is mainly pursued through increased renewable energy production and hence reduced fossil fuel exploitation and reduced greenhouse gas (GHG) emissions. With this, the EEG, at least in theory, addresses two of the ecological ceilings of the donut, namely climate change and air pollution. According to the German Environment Agency (Umweltbundesamt, UBA) the amount of avoided GHG emissions due to the use of renewable energies increased from ~45 Mt CO2eq in 2000 to ~220 Mt CO2eq in 2020. (UBA, 2022b) This corresponds to around 30% of Germanys total GHG emissions in 2020. (UBA, 2022a) However, while these numbers are true and impressive, the real overall emission reductions due to the EEG are hard to quantify an according to experts probably rather low. (Pötter, 2020) The reasons for this are shortcomings in the European Emissions Trading System (ETS) which are termed the waterbed effect. (Appunn, 2019) These shortcomings have been addressed only in the 2019 revision of the ETS. Before that, emission savings in one country or sector would lead to the same amount of emissions increase elsewhere due to an inefficient ETS cap. Therefore, in terms of climate and environmental protection, a European framework or a higher carbon price would probably have had a greater impact than the EEG. (Pötter, 2020)</p>
        <p>In terms of social foundations of the donut the EEG clearly contributes to energy, income and work, as well as networks. The EEG in particular reveals how these three foundations are strongly interconnected. The supply with (clean) energy is one of the main goals of the EEG and looking at the data in Figure 1 (see above) it is clearly on the right track. At the same time the efforts in providing this clean energy have created a large number of new jobs. The number of employees in the renewable energy sector in Germany has grown between 2000 and 2011 by a factor of four (from around 100.000 to 400.000). (UBA, 2022d) Furthermore the support mechanism of the EEG provides possibilities for (additional) income not only for powerful investors who are able to invest big amounts of money into large scale renewable energy power plants, but also for small scale land or property owners who can invest in e.g. photovoltaics on their own rooftop or farm and sell their surplus of electricity to the electricity supply companies. In addition, the EEG gives a special role to so called ‘citizens energy cooperatives’ (Bürgerenergiegenossenschaften), which are networks of individuals who jointly invest into renewable energy production. They are used in the EEG as a tool to enhance the diversity of actors and stakeholders for the energy transition. When fulfilling certain criteria in terms of number of individual members and distribution of voting rights, the cooperatives get priority rights and other advantages in the approval process for renewable energy power plants. (BMWK, 2022a) The number of energy cooperatives in Germany has grown form around 100 in the year 2000 to close to 2000 today. (Kahla et al., 2017) These citizens energy networks are a great example how strong networks of local individuals can generate income and work and at the same time produce clean renewable energy for the society.</p>
        <p>Another, more subtle and broader contribution to building a strong network is the financing mechanism of the EEG itself. Since it is based on the EEG surcharge, which (almost) every electricity consumer pays, it is based on the shared burden principle. This means that all consumers jointly pay for the transformation of the energy system. This is in clear contrast to a system where the state would pay directly for the transition via state subsidies or direct-payments. Such a system, where the state is involved much more directly, would be more fragile and vulnerable to changes in government policies. (Gröschel & Geheeb, 2007) In this context it should be noted that since 2021 the EEG surcharge is supported by money from the federal government budget and since June 2022 the surcharge is reduced to 0 ct and entirely paid by the government budget. However, the overall mechanism is unchanged and the financing of renewables still happens through the EEG surcharge (payed for by the government) but not through direct payments of the government. (Bundesnetzagentur, 2022)</p>

        <h2>V. Critique on the EEG</h2>
        <p>In addition to the questionable effect in terms of climate and environmental protection of the EEG (see above), there are three major lines of criticism on the EEG. The first one is along the deployment corridors, annual expansion targets and related caps for support of new projects. The early versions of the EEG were lacking defined deployment corridors for the renewable technologies completely, which resulted in a lack of controllability and planning security. (BMWK, 2022c) Starting with the EEG revision in 2012 clear deployment corridors for the electricity sector were defined in the EEG. (BMWK, 2022b) The overall critique about these corridors was for long time that they are not in line with climate protection goals and the Paris Agreement. (BUND, 2016) On the other hand, to keep the costs of the energy transition under control, the number of new installations for each renewable energy technology was limited for each year. Furthermore, depending on the technology, the financial support for each new installation is reduced the more installations had been made already in a given year. This so called ‘breathing cap’ is, especially for the solar technologies, harshly criticized as slowing down the speed of the energy transition unnecessarily. (Photovoltaik-Symposium, 2021; HTW, 2020)</p>
        <p>The second line of criticism regards exemptions for large electricity consumers from the EEG surcharge. Companies and industries that have a yearly electricity consumption over a certain limit and whose electricity costs amounts to a certain percentage of their gross value added would have to pay only a strongly reduced EEG surcharge. The limits in terms of consumption and percentage of their gross value added were over the course of the EEG revisions constantly reduced and hence the circle of companies that were favored by the exemptions grew a lot. As a result, the energy-intensive industries consumed at some point 18 percent of the electricity in Germany, but contributed only 0.3 percent of the financing of the energy transition through the EEG surcharge. (Photovoltaik.org, 2022) This imbalance understandably was in the focus of the critique. Furthermore, the regulations exempting large consumers form the EEG surcharge was criticized to enhance the energy consumption of large consumers more instead of creating incentives for energy efficiency and energy saving strategies. (Wetzel, 2020)</p>
        <p>The third mayor criticism, which refers mostly to the speed of wind power plant expansion, is related to the changes in the support mechanism away from fixed feed-in tariffs towards an auction scheme which got implemented in 2017. The entire application process involved in the auction scheme became significantly more complex resulting in an overall reduction of incoming applications. In addition, the processing time of the applications extended notably. (Seynsche & Hanke-Rauschenbach, 2019) This resulted in a strong reduction of wind energy installations per year. While in the years 2014-2017 around 4000-5000 MW wind power had been installed each year, this number dropped by more than 50% and was in the years 2018-2020 at well below 2000 MW per year. (Windbranche.de, 2022)</p>

        <h2>VI. Conclusions and International Context</h2>
        <p>Despite some flaws and imperfections, the EEG can certainly be framed as a success story. It has boosted the deployment of renewable energies in Germany (compare Figure 1 above) and at the same time achieved a significant reduction in production cost of many renewable technologies as can be seen in Figure 2. In particular the reduced production costs enabled the market entry for these technologies as they are now competitive with conventional power sources even without the support mechanisms of the EEG. (Römermann & Kemfert, 2020) The associated technological developments were strongly driven by the German EEG, but obviously these technologies are being applied worldwide now. In addition to the technological developments that leave their impact internationally also the EEG itself has been ‘exported’ into numerous countries and today there are more than 100 countries that have adopted renewable energy acts that are based on the mechanisms of the EEG. (Römermann & Kemfert, 2020)</p>
        <div className={styles.articleImageContainer}>
          <img src="/simon/3.png" alt="doughnut" height="auto" />
          <span>Fig.3. Levelized cost of electricity for new sloar and wind versus running cost of existing coal- and gas-fired power plants, 2014-2021. Figure taken from (Enkhardt, 2021)</span>
        </div>

        <h2>References</h2>
        <ol start="1" className={styles.referenceList}>
          <li>Appunn, K. (2019, April 5). National climate measures and European emission trading: Assessing the ‘waterbed effect.’ Clean Energy Wire. Retrieved September 2, 2022, from https://www.cleanenergywire.org/factsheets/national-climate-measures-and- european-emission-trading-assessing-waterbed-effect</li>
          <li>BUND. (2016, March 2). EEG-Entwurf verstößt gegen Ziele des Pariser Klimaschutzabkommens. BUND für Naturschutz und Umwelt in Deutschland. Retrieved September 2, 2022, from https://www.bund.net/service/presse/pressemitteilungen/detail/news/eeg-entwurf- verstoesst-gegen-ziele-des-pariser-klimaschutzabkommens/</li>
          <li>Bundesanzeiger. (1990, December 14). Gesetz über die Einspeisung von Strom aus erneuerbaren Energien in das öffentliche Netz (Stromeinspeisungsgesetz). Bundesgesetzblatt. Retrieved September 2, 2022, from https://www.bgbl.de/xaver/bgbl/start.xav?start=//*%5B@attr_id=%27bgbl190s2633b. pdf%27%5D#__bgbl__%2F%2F*%5B%40attr_id%3D%27bgbl190s2633b.pdf%27% 5D__1662153858968</li>
          <li>Bundesministerium für Wirtschaft und Klimaschutz (BMWK). (2022a). Akteursvielfalt/Bürgerenergie. Informationsportal Erneuerbare Energien. Retrieved September 2, 2022, from https://www.erneuerbare- energien.de/EE/Navigation/DE/Recht-Politik/EEG-Ausschreibungen/Akteursvielfalt- Buergerenergie/akteursvielfalt-buergerenergie.html</li>
          <li>Bundesministerium für Wirtschaft und Klimaschutz (BMWK). (2022b). Eckpunkte der EEG- Novelle 2012 sowie sonstige Neuerungen für erneuerbare Energien. Informationsportal Erneuerbare Energien. Retrieved September 2, 2022, from https://www.erneuerbare- energien.de/EE/Redaktion/DE/Dossier/eckpunkte_der_eeg_novelle.html</li>
          <li>Bundesministerium für Wirtschaft und Klimaschutz (BMWK). (2022c). EEG-Reform. Informationsportal Erneuerbare Energien. Retrieved September 2, 2022, from https://www.erneuerbare-energien.de/EE/Navigation/DE/Recht- Politik/EEG_Reform/eeg_reform.html</li>
          <li>Bundesministerium für Wirtschaft und Klimaschutz (BMWK). (2022d). Erneuerbare- Energien-Gesetz. Informationsportal Erneuerbare Energien. Retrieved September 2, 2022, from https://www.erneuerbare-energien.de/EE/Redaktion/DE/Dossier/eeg.html</li>
          <li>Bundesministerium für Wirtschaft und Klimaschutz (BMWK). (2022e). Recht und Zuständigkeiten. Informationsportal Erneuerbare Energien. Retrieved September 2, 2022, from https://www.erneuerbare- energien.de/EE/Navigation/DE/Technologien/Windenergie-auf-See/Rechtlicher- Rahmen/Rechtsnormen/rechtsnormen.html</li>
          <li>Bundesnetzagentur. (2022). EEG-Umlage. Retrieved September 2, 2022, from https://www.bundesnetzagentur.de/SharedDocs/A_Z_Glossar/E/EEG_Umlage.html</li>
          <li>Diermann, R. (2020, February 25). 20 Jahre EEG: „Erfolgreichstes Klimaschutzgesetz in der Geschichte der Menschheit“. pv magazine Deutschland. Retrieved September 2, 2022, from https://www.pv-magazine.de/2020/02/25/20-jahre-eeg-erfolgreichstes- klimaschutzgesetz-in-der-geschichte-der-menschheit/</li>
          <li>EEG 2021. (2021, January 1). Bundesamt Für Justiz. Retrieved September 2, 2022, from http://www.gesetze-im-internet.de/eeg_2014/index.html</li>
          <li>Enkhardt, S. (2021, June 23). BNEF: Globale Stromgestehungskosten für Photovoltaik auf 4,8 US-Dollarcent pro Kilowattstunde gesunken. pv magazine Deutschland. Retrieved September 2, 2022, from https://www.pv-magazine.de/2021/06/23/bnef-globale- stromgestehungskosten-fuer-photovoltaik-auf-48-us-dollarcent-pro-kilowattstunde- gesunken/</li>
          <li>Gröschel, & Geheeb. (2007, July). EEG - THE RENEWABLE ENERGY SOURCES ACT - The success story of sustainable policies for Germany. Federal Ministry for the Environment, Nature Conservation and Nuclear Safety (BMU).</li>
          <li>Hochschule für Technik und Wirtschaft (HTW). (2020, March). Deckelstudie: Ausbaubremse Photovoltaik-Zubaudeckel Geht der Photovoltaik aufgrund des atmenden Zubaudeckels die Puste aus? https://solar.htw-berlin.de/studien/deckelstudie/</li>
          <li>Kahla, F., Holstenkamp, L., Müller, J. R., & Degenhart, H. (2017, May). Development and State of Community Energy Companies and Energy Cooperatives in Germany. Leuphana University of Lüneburg.</li>
          <li>Photovoltaik.org. (2022). EEG-Umlage: Ausnahmen für energieintensive Betriebe. Retrieved September 2, 2022, from https://www.photovoltaik.org/wissen/eeg-umlage- ausnahmen-fuer-energieintensive-betriebe</li>
          <li>Photovoltaik-Symposium 2021. (2021, May). Erklärung des Photovoltaik-Symposiums 2021 zur Erreichung der Klimaschutzziele nach dem Beschluss des Bundesverfassungsgerichtes.</li>
          <li>Pötter, B. (2020, April 6). Gemischte Bilanz des EEG: Weniger CO2? Na ja . . .. TAZ Verlags- und Vertriebs GmbH. Retrieved September 2, 2022, from https://taz.de/Gemischte-Bilanz-des-EEG/!5673553/</li>
          <li>Ritchie, H. (2020, November 28). Renewable Energy. Our World in Data. Retrieved September 2, 2022, from https://ourworldindata.org/renewable-energy</li>
          <li>Römermann, S., & Kemfert, C. (2020, February 25). Ökonomin zu 20 Jahre EEG - Ein “verschlimmbesserter” Erfolg. Deutschlandfunk. Retrieved September 2, 2022, from https://www.deutschlandfunk.de/oekonomin-zu-20-jahre-eeg-ein- verschlimmbesserter-erfolg-100.html</li>
          <li>Seynsche, M., & Hanke-Rauschenbach, R. (2019, December 11). Ausbau Erneuerbarer Energien - “Das erste Drittel der Energiewende hat prima geklappt.” Deutschlandfunk. Retrieved September 2, 2022, from https://www.deutschlandfunk.de/ausbau-erneuerbarer-energien-das-erste-drittel-der- 100.html</li>
          <li>Umweltbundesamt (UBA). (2021, September 10). Erneuerbare-Energien-Gesetz. Umweltbundesamt. Retrieved September 2, 2022, from https://www.umweltbundesamt.de/themen/klima-energie/erneuerbare- energien/erneuerbare-energien-gesetz#erfolg</li>
          <li>Umweltbundesamt (UBA). (2022a, March 15). Treibhausgas-Emissionen in Deutschland. Umweltbundesamt. Retrieved September 2, 2022, from https://www.umweltbundesamt.de/daten/klima/treibhausgas-emissionen-in- deutschland#emissionsentwicklung</li>
          <li>Umweltbundesamt (UBA). (2022b, March 25). Erneuerbare Energien – Vermiedene Treibhausgase. Umweltbundesamt. Retrieved September 2, 2022, from https://www.umweltbundesamt.de/daten/energie/erneuerbare-energien-vermiedene- treibhausgase#undefined</li>
          <li>Umweltbundesamt (UBA). (2022c, March 28). Indicator: Renewable energy. Umweltbundesamt. https://www.umweltbundesamt.de/en/data/environmental- indicators/indicator-renewable-energy</li>
          <li>Umweltbundesamt (UBA). (2022d, August 24). Indicator: Employment in the renewable energy sector. Umweltbundesamt. Retrieved September 2, 2022, from https://www.umweltbundesamt.de/en/data/environmental-indicators/indicator- employment-in-the-renewable-energy-sector#at-a-glance</li>
          <li>Wetzel, D. (2020, December 1). Öko-Unsinn EEG: Stromverschwendung wird belohnt. DIE WELT. Retrieved September 2, 2022, from https://www.welt.de/wirtschaft/article221395314/Oeko-Unsinn-EEG- Stromverschwendung-wird-belohnt.html</li>
          <li>Windbranche.de. (2022). Windenergie Markt in Deutschland. Retrieved September 2, 2022, from https://www.windbranche.de/windenergie-ausbau/deutschland</li>
        </ol>
      </div>
    </main>
  </div>
) }
